### (passed) Get all products (body)
POST https://localhost:7170/api/Product/getAll
Content-Type: application/json

{
  "id": null
}

### (passed) Get all products (body)
GET https://localhost:7170/api/Product
Content-Type: application/json

{
  "id": []
}

### (passed)  Create product
POST https://localhost:7170/api/Product
Content-Type: application/json

{
  "command": [
    
    {
      "name": "{{$random.alphabetic(10)}}",
      "price": 10,
      "description": null,
      "code": "{{$random.float(10.2)}}"
    },
     {
      "name": "{{$random.alphabetic(10)}}",
      "price": 30,
      "description": null,
      "code": "{{$random.float(10.2)}}"
    }

  ]
}

### (passed) get a product by id (body) 
GET https://localhost:7170/api/Product/GetById/
Content-Type: application/json

{
  "id": "73b3cb2f-77a2-41e5-ae86-014ba18883b"
}

### (passed) get a product by id (query)
GET https://localhost:7170/api/Product/73b3cb2f-77a2-41e5-ae86-014ba188843

### (passed)delete product as list
DELETE https://localhost:7170/api/Product/
Content-Type: application/json

{
  "id": [
    "0bcd7063-3d9a-4d50-9e48-5cd11c7a6fff",
    "f1b7579a-f12c-4396-9545-00e81b7610a8"
  ]
}

### (passed) get list of product
POST https://localhost:7170/api/Product/getAll
Content-Type: application/json

{
  "id": null
}

### (passed) update product
PUT https://localhost:7170/api/Product/
Content-Type: application/json

{
  "command": [
    {
      "id": "05ecfab3-87c7-4976-9185-c902c7ef8f2c",
      "name": "Tessst",
      "price": 1110,
      "description": "desss"
    }
  ]
}
