### (Completed) Get all Stocking in get No.27
GET https://localhost:7170/api/Stock/Getall
Content-Type: application/json

{
  "id": [
    "FA3E2999-712B-44B8-914B-CEE41EF3A184",
    "2D103841-9BF0-49E6-AEB1-DDA8A225824C"
  ]
}

###(Completed) Get all Stocking in post No.83
POST https://localhost:7170/api/Stock
Content-Type: application/json

{
  "id": null
}
###(completed) Get By Id query string No.138
GET https://localhost:7170/api/Stock/FA3E2999-712B-44B8-914B-CEE41EF3A184

### (Completed) Get By Id Body 
GET https://localhost:7170/api/Stock/GetById
Content-Type: application/json

{
  "id": null
}

### (completed) Get By ProductId
GET https://localhost:7170/api/Stock/GetByProduct
Content-Type: application/json

{
  "ProductId": null
}

###(completed) Post By ProductId
POST https://localhost:7170/api/Stock/GetByProduct
Content-Type: application/json

{
  "ProductId": null
}


###(On Developed) get list create
POST https://localhost:7170/api/Stock/Create
Content-Type: application/json

{
  "command": [
      {
        "productcode": "P-0001",
        "warecode": "A-0001",
        "quantity": 500
      }
  ]
  
}

###(passed) get by Productcode(get)
GET https://localhost:7170/api/Stock/GetByProductCodes
Content-Type: application/json

{
  "productcodes": [
    "P-0001"
  ]
}

###(passed) get by Productcode
POST https://localhost:7170/api/Stock/GetByProductCodes
Content-Type: application/json

{
  "productcodes": [
    "P"
  ]
}



###(completed) Updated
PUT https://localhost:7170/api/Stock
Content-Type: application/json

{
  "command": [
    {
      "id" : "2D103841-9BF0-49E6-AEB1-DDA8A225824C",
      "quantity": 800
    }
  ]
}